<a href="https://colab.research.google.com/github/znumunz/dataviz2025/blob/main/Copy_of_midterm2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ผู้ร้ายชื่อ Joe Germuska
# ID ผู้บงการ ผู้บงการ id 918773


ให้สืบหาฆาตรกร (10 คะแนน) และ ผู้บงการ (5 คะแนน) ในคดี ฆาตรกรรม (murder) ที่เกิดขึ้นในวันที่ 15 มกราคม 2018 ที่เมือง Pandas City โดยเริ่มจากการตรวจสอบ ข้อมูลคดีในไฟล์ crime_scene_report.csv

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
path = '/content/drive/MyDrive/Middataviz'

In [22]:
cri_rp = pd.read_csv(path + '/crime_scene_report.csv')
cri_rp

,date,type,description,city
0,20180115,robbery,A Man Dressed as Spider-Man Is on a Robbery Spree,NYC
1,20180115,murder,Life? Dont talk to me about life.,Albany
2,20180115,murder,"Mama, I killed a man, put a gun against his he...",Reno
3,20180215,murder,REDACTED REDACTED REDACTED,Pandas City
4,20180215,murder,Someone killed the guard! He took an arrow to ...,Pandas City
...,...,...,...,...
1223,20180430,bribery,\n,Garden Grove
1224,20180430,fraud,‘Why not?’ said the March Hare.\n,Houma
1225,20180430,assault,\n,Fontana
1226,20180501,assault,be NO mistake about it: it was neither more no...,Trenton
1227,20180115,murder,Security footage shows that there were 2 witne...,Pandas City

In [28]:
murder_pandascity_20180115 = cri_rp[(cri_rp['type']=='murder') & (cri_rp['date']==20180115) & (cri_rp['city']=='Pandas City')]

1227    Security footage shows that there were 2 witne...
Name: description, dtype: object

In [61]:
pd.set_option('display.max_colwidth', None)
display(murder_pandascity_20180115['description'])

1227    Security footage shows that there were 2 witnesses. The first witness lives at the last house on "Northwestern Dr". The second witness, named Annabel, lives somewhere on "Franklin Ave".
Name: description, dtype: object


**ภาพจากกล้องวงจรปิดแสดงให้เห็นว่ามีพยาน 2 คน พยานคนแรกอาศัยอยู่ที่บ้านหลังสุดท้ายบนถนน "Northwestern Dr" ส่วนพยานคนที่สองชื่อแอนนาเบล อาศัยอยู่ที่ไหนสักแห่งบนถนน "Franklin Ave"**

In [48]:
crime = pd.read_csv(path + '/crime_scene_report.csv')
driven_license = pd.read_csv(path + '/drivers_license.csv')
facebook_event_checkin = pd.read_csv(path + '/facebook_event_checkin.csv')
income = pd.read_csv(path + '/income.csv')
get_fit_now_check_in = pd.read_csv(path + '/get_fit_now_check_in.csv')
get_fit_now_member = pd.read_csv(path + '/get_fit_now_member.csv')
interview = pd.read_csv(path + '/interview.csv')
person = pd.read_csv(path + '/person.csv')

In [57]:
print(crime.columns)
print(driven_license.columns)
print(facebook_event_checkin.columns)
print(get_fit_now_check_in.columns)
print(get_fit_now_member.columns)
print(income.columns)
print(interview.columns)
print(person.columns)

Index(['date', 'type', 'description', 'city'], dtype='object')
Index(['id', 'age', 'height', 'eye_color', 'hair_color', 'gender',
       'plate_number', 'car_make', 'car_model'],
      dtype='object')
Index(['person_id', 'event_id', 'event_name', 'date'], dtype='object')
Index(['membership_id', 'check_in_date', 'check_in_time', 'check_out_time'], dtype='object')
Index(['id', 'person_id', 'name', 'membership_start_date',
       'membership_status'],
      dtype='object')
Index(['ssn', 'annual_income'], dtype='object')
Index(['person_id', 'transcript'], dtype='object')
Index(['id', 'name', 'license_id', 'address_number', 'address_street_name',
       'ssn'],
      dtype='object')

In [167]:
person_Dr = person[person['address_street_name']=='Northwestern Dr'].head()

In [107]:
address_number_max = person_Dr['address_number'].max()
address_number_max

4919

## หาคนข้อมูลพยานคนแรก

In [94]:
person[person['address_number']==address_number_max]

,id,name,license_id,address_number,address_street_name,ssn
499,14887,Morty Schapiro,118009,4919,Northwestern Dr,111564949

## ถอดเสียงการสัมภาษณ์

In [222]:
interview[interview['person_id']==14887]

,person_id,transcript
4988,14887,"I heard a gunshot and then saw a man run out. He had a ""Get Fit Now Gym"" bag. The membership number on the bag started with ""48Z"". Only gold members have those bags. The man got into a car with a plate that included ""H42W""."

## ผมได้ยินเสียงปืน แล้วก็เห็นผู้ชายคนหนึ่งวิ่งออกมา เขามีกระเป๋าที่เขียนว่า "Get Fit Now Gym" หมายเลขสมาชิกบนกระเป๋าเริ่มต้นด้วย "48Z" ซึ่งมีเฉพาะสมาชิกระดับ Gold เท่านั้นที่ได้กระเป๋าแบบนี้ ผู้ชายคนนั้นขึ้นรถที่มีป้ายทะเบียนซึ่งมีตัวอักษร "H42W" อยู่ด้วย

#ผู้ต้องสงสัย

In [136]:
get_fit_now_member[
    (get_fit_now_member['membership_status'] == 'gold') &
    (get_fit_now_member['id'].str.startswith('48Z'))
]

        id  person_id           name  membership_start_date membership_status
181  48Z7A      28819   Joe Germuska               20160305              gold
182  48Z55      67318  Jeremy Bowers               20160101              gold

## ผู้ชายคนนั้นขึ้นรถที่มีป้ายทะเบียนซึ่งมีตัวอักษร "H42W" อยู่ด้วย

In [205]:
drivers[drivers['plate_number'].str.startswith('H42W')]

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
915,183779,21,65,blue,blonde,female,H42W0X,Toyota,Prius

In [210]:
person[person['id']==183779]

Empty DataFrame
Columns: [id, name, license_id, address_number, address_street_name, ssn]
Index: []

In [212]:
interview[interview['person_id']==183779]

Empty DataFrame
Columns: [person_id, transcript]
Index: []

## หาคนข้อมูลพยานคนที่สอง ชื่อแอนนาเบล อาศัยอยู่ที่ไหนสักแห่งบนถนน "Franklin Ave"

In [174]:
Franklin = person[(person['address_street_name']=='Franklin Ave')&(person['name'].str.startswith('Annabel'))]
Franklin.head()

,id,name,license_id,address_number,address_street_name,ssn
665,16371,Annabel Miller,490173,103,Franklin Ave,318771143

In [187]:
interview = pd.read_csv(path + '/interview.csv')

In [186]:
interview[interview['person_id']==16371]

,person_id,transcript
4989,16371,"I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th."

## ฉันเห็นเหตุการณ์ฆาตกรรมเกิดขึ้น และฉันจำคนร้ายได้จากยิมของฉัน ตอนที่ฉันกำลังออกกำลังกายในสัปดาห์ที่แล้ว วันที่ 9 มกราคม

# ผู้บงการ id 918773
ฉันได้รับการว่าจ้างจากผู้หญิงคนหนึ่งซึ่งมีเงินมาก ฉันไม่ทราบชื่อของเธอ แต่รู้ว่าเธอสูงประมาณ 5 ฟุต 5 นิ้ว (65 นิ้ว) หรือ 5 ฟุต 7 นิ้ว (67 นิ้ว) เธอมีผมสีแดง และเธอขับรถ Tesla Model S ฉันทราบว่าเธอเข้าร่วมคอนเสิร์ต SQL Symphony ทั้งหมด 3 ครั้งในเดือนธันวาคม ปี 2017

In [213]:
drivers[
    (drivers['hair_color'] == 'red') &
    (drivers['car_make'] == 'Tesla') &
    (drivers['height'].isin([65, 67]))
]

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
9078,918773,48,65,black,red,female,917UU3,Tesla,Model S

In [219]:
person[person['id']==918773]

Empty DataFrame
Columns: [id, name, license_id, address_number, address_street_name, ssn]
Index: []

#หาคนร้าย

In [201]:
members_48Z = get_fit_now_member[get_fit_now_member['id'].str.startswith('48Z')]
merged_check_ins = pd.merge(members_48Z, get_fit_now_check_in, left_on='id', right_on='membership_id', how='left')
display(merged_check_ins)

,id,person_id,name,membership_start_date,membership_status,membership_id,check_in_date,check_in_time,check_out_time
0,48Z38,49550,Tomas Baisley,20170203,silver,48Z38,20170611,813,1122
1,48Z38,49550,Tomas Baisley,20170203,silver,48Z38,20171212,1150,1153
2,48Z38,49550,Tomas Baisley,20170203,silver,48Z38,20170820,919,921
3,48Z38,49550,Tomas Baisley,20170203,silver,48Z38,20180314,315,1150
4,48Z38,49550,Tomas Baisley,20170203,silver,48Z38,20170120,482,1138
5,48Z7A,28819,Joe Germuska,20160305,gold,48Z7A,20180109,1600,1730
6,48Z55,67318,Jeremy Bowers,20160101,gold,48Z55,20180109,1530,1700